root: true

extends:
  - 'eslint:recommended'
  - 'plugin:import/react'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:react/recommended'
  - 'plugin:jsx-a11y/recommended'

plugins:
  - import
  - react
  - jsx-a11y
  - prettier

parser: babel-eslint

parserOptions:
  ecmaVersion": 2018

env:
  browser: true
  es6: true

settings:
  import/resolver:
    node:
      extensions:
        - '.js'
        - '.jsx'

overrides:
  - files:
      - webpack.*.js
      - postcss.*.js
    env:
      browser: false
      node: true
    settings:
      import/resolver: node

rules:
  prettier/prettier: warn
  react/prop-types: off

  max-len:
    - error
    - code: 128

  semi:
    - error
    - never
